apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Values.app.name }}
 namespace: {{ .Values.app.namespace }}
data:
  {{- range $key, $val := .Values.appConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}

